users=[
    {
        name:'sangu',
        user:'sangu4403',
        pass:'nmit@123'
    },
    {
        name:'admin',
        user:'admin',
        pass:'admin'
    },
    {
        name:'auth',
        user:'auth',
        pass:'auth'
    }
]

module.exports={users:users};